GET http://localhost:3000/api/todo

###
POST http://localhost:3000/api/todo
Content-Type: application/json

{
  "title": "강의 듣기"
}

PATCH http://localhost:3000/api/todo
Content-Type: application/json

{
  "title": "강의 듣기"
}

###
GET http://localhost:3000/api/todo/65d75ce0ee3b3e412ed5ee12

###
PATCH http://localhost:3000/api/todo/65d75ce0ee3b3e412ed5ee12
Content-Type: application/json

{
  "newIndex": 0
}

###
DELETE http://localhost:3000/api/todo/65d72d39c713272729639e18